name: angle_utils
description: A small and compact utility library for dealing with all kinds of angles
version: 0.0.4
repository: https://github.com/daniel-riffi/angle_utils

environment:
  sdk: ^3.0.5

dependencies:

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
